# Generated by Django 4.2.1 on 2023-08-23 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='limit_per_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='limit_per_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 23)),
        ),
    ]
